### ISSUE TITLE
在Debian12 gnome desktop下无法启动

### ISSUE THREAD

**Issue by Gavin1937** [hiroi-sora/Umi-OCR_runtime_linux#1]
Debian12 gnome desktop下无法启动。

* python version: 3.11.2

应该是没有正确加载QtQuick模组导致的。QtQuick.2 已经正确安装到venv里面了。

![image](https://github.com/hiroi-sora/Umi-OCR_runtime_linux/assets/71205842/477d935f-cde9-47cf-b6ca-9c16bf0f1721)

我尝试了以下方案都没用：
1. 手动把venv里面所有的Qt `.so` 文件用LD_LIBRARY_PATH指定
2. 或者设置 `QTDIR`、`QML_IMPORT_PATH`、和`QML2_IMPORT_PATH`
3. 或者直接再系统里装 `python3-pyside2*` 相关的包。

**Comment by Gavin1937** [comment]
都不行，相对绝对路径都不行，一样的错误。也许是我系统的问题、或者没有配置对

**Comment by hiroi-sora** [comment]
解决了一个类似的问题，也许能给你参考。

系统： Ubuntu 22.04

症状：

在 VS Code 内置终端中，**可以**使用下列简单指令，手动启动程序。

```sh
UmiOCR-data/venv/bin/python3 UmiOCR-data/main_linux.py
```

会打印下列警告，但影响不大，主窗口可以显示。
```
QSocketNotifier: Can only be used with threads started with QThread
```

而在**系统终端**中，使用相同的指令启动程序，会在下面这行代码异常退出：

UmiOCR-data/py_src/run.py
```python
    qtApp = QGuiApplication(sys.argv)
```

报错信息：
```
~/MyCode/Umi-OCR_Project/Umi-OCR$ UmiOCR-data/venv/bin/python3 UmiOCR-data/main_linux.py

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

已中止 (核心已转储)
```

----

排查问题：

1. 设置环境变量，提高QT日志级别：
```sh
export QT_DEBUG_PLUGINS=1
```
2. 重试 `main_linux.py` ，打印出如下的日志信息：
```sh
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QFactoryLoader::QFactoryLoader() checking directory path "/home/my/MyCode/Umi-OCR_Project/Umi-OCR/UmiOCR-data/venv/lib/python3.10/site-packages/PySide2/Qt/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/home/my/MyCode/Umi-OCR_Project/Umi-OCR/UmiOCR-data/venv/lib/python3.10/site-packages/PySide2/Qt/plugins/platforms/libqeglfs.so"
Found metadata in lib /home/my/MyCode/Umi-OCR_Project/Umi-OCR/UmiOCR-data/venv/lib/python3.10/site-packages/PySide2/Qt/plugins/platforms/libqeglfs.so, metadata=
```
上述日志指出 `libqeglfs.so` 这个文件有问题。

3. 接下来参考 [这篇文章](https://cloud.tencent.com/developer/article/1726400) ，查询该文件的关联：
```sh
ldd libqxcb.so
```
发现有一个依赖项缺失：
```
	libxcb-xinerama.so.0 => not found
```
4. 安装该依赖：
```sh
sudo apt-get install libxcb-xinerama0
```
5. 在系统终端重试 `main_linux.py` ，已经能启动主界面了。

![image](https://github.com/hiroi-sora/Umi-OCR_runtime_linux/assets/56373419/6a5c8cdc-ef50-44b1-a17e-3c804a837d5a)

不过比较奇怪的是为什么在 VSC 终端中不会受到该文件缺失的影响。也许 VSC 终端使用的不是 xcb ？

在某些系统中也会存在 [xcb缺失](https://blog.csdn.net/sinat_26106275/article/details/82778951) 类似的坑，值得留意。

**Comment by Gavin1937** [comment]
不太行。打开debug log之后没发现有什么依赖缺失的问题，所有依赖都正常安装了。只能是在启动时没有正确找到QtQuick了。我没有用vscode或者其他ide，全部是手动配置的环境，可能是那一步没弄对。

不过这是开发环境，配置起来麻烦也正常。加上Umi-OCR的项目架构本来就复杂，姑且把这个issue看成是环境没有配置好吧。

debug日志：
[debug.txt](https://github.com/user-attachments/files/15597795/debug.txt)

**Comment by hiroi-sora** [comment]
我在 Debian12 系统中复现了相同问题，并搞懂了原因。

Umi-OCR依赖的PySide2版本是 `5.15.x` 。而 Debian12 中，pip支持安装的最新版本是 `5.13` 。这就导致Umi-OCR以下的代码无法运行：

Main.qml
```qml
import QtQuick 2.15
```

报错：
```
module "QtQuick" version 2.15 is not installed
```

---

解决方法1（不可行）：降低代码中 `QtQuick` 等包的版本，比如
```qml
import QtQuick 2.10
```
不可行：Umi-OCR依赖一些较新的qml API，在落后的包中无法实现。

解决方法2：

在 Debian 中，手动从源码编译最新的 PySide2 库。

**Comment by Gavin1937** [comment]
python 版本也有限制

![image](https://github.com/hiroi-sora/Umi-OCR_runtime_linux/assets/71205842/448afe48-acc3-42cb-9371-8fabef6f43ab)

**Comment by Gavin1937** [comment]
> Umi-OCR依赖一些较新的qml API，在落后的包中无法实现。

有没有可能直接把那些依赖新qml API的模块给禁用了？

**Comment by Gavin1937** [comment]
行了

![image](https://github.com/hiroi-sora/Umi-OCR_runtime_linux/assets/71205842/ecb861e0-a4e7-4614-ad5b-04f345fbe62f)

Debian开发者需要自行安装Python 3.10（网上基本没有现成的安装包，需要自己编译），之后pip就可以正常安装PySide2 5.15了。
