### ISSUE TITLE
Docker部署无法执行OCR： "code": 803, "data": "任务提前结束。[Error] OCR init fail."

### ISSUE THREAD

**Issue by weiweics55** [hiroi-sora/Umi-OCR_runtime_linux#3]
http://localhost:1224/api/ocr

{"code": 803, "data": "\u4efb\u52a1\u63d0\u524d\u7ed3\u675f\u3002[Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 2, 'config_path': 'models/config_chinese.txt', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 960}\nOCR init fail."}
json: cannot unmarshal string into Go struct field Response.data of type []local.DataEntry

**Comment by hiroi-sora** [comment]
这个问题是OCR引擎没有运行起来。很大可能是CPU不具有AVX指令集，所以不兼容。

请检查CPU兼容性（在主机或容器执行均可）：
```
lscpu | grep avx
```
如果CPU支持AVX指令集，则会输出一行很长的结果，其中可以找到 avx 的字样，类似如下：
```
Flags:          ... avx ... avx2 ...
```

**Comment by hiroi-sora** [comment]
看来CPU是没有问题的。请尝试在容器中，运行以下路径的脚本：
```
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/run.sh
```
正常情况下，应该能看到 `OCR init completed.` 的输出。

如果有报错或别的情况，请告诉我。

**Comment by weiweics55** [comment]
[root@VM-0-3-centos Umi-OCR-Docker]# docker ps -a
CONTAINER ID   IMAGE            COMMAND             CREATED         STATUS         PORTS                                       NAMES
a90cb508e2f5   umi-ocr-paddle   "/app/umi-ocr.sh"   4 minutes ago   Up 4 minutes   0.0.0.0:1224->1224/tcp, :::1224->1224/tcp   umi-ocr
[root@VM-0-3-centos Umi-OCR-Docker]# docker exec -it a90cb508e2f5 /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/run.sh
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/libopencv_imgcodecs.so.410)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/libopencv_imgcodecs.so.410)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/libopencv_imgcodecs.so.410)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/libopencv_imgcodecs.so.410)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/libopencv_imgproc.so.410)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/libopencv_imgproc.so.410)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/libopencv_core.so.410)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/libopencv_core.so.410)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/libopencv_core.so.410)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/libopencv_core.so.410)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/libopencv_core.so.410)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/libopencv_core.so.410)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/libgomp.so.1)
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/bin/PaddleOCR-json: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/libgomp.so.1)
[root@VM-0-3-centos Umi-OCR-Docker]#

**Comment by hiroi-sora** [comment]
请先删除当前的容器。然后，打开主机中下载的Dockerfile，前面有一行：
```
FROM debian:11-slim
```
请尝试将它改为版本更靠后的基础镜像，如：
```
FROM debian:12-slim
```
然后，重新build和run。

**Comment by pluto-ljl** [comment]
我是本地部署遇到了这个问题，原因是 `libc6` 和 `libstdc++` 版本过低，解决办法是手动下载所需版本的库文件，放到插件的 `lib`目录下，再修改插件的启动文件。

从 https://pkgs.org/ 搜索需要下载的文件，最终定位到需要下载以下两个文件：

```
http://ftp.de.debian.org/debian/pool/main/g/gcc-12/libstdc++6_12.2.0-14_amd64.deb
http://ftp.de.debian.org/debian/pool/main/g/glibc/libc6_2.36-9+deb12u7_amd64.deb
```

这两个文件下载下来之后，用归档管理器打开，再打开其中的 `data.tar.xz`。
把 `/usr/lib/x86_64-linux-gnu/` 或 `/lib/x86_64-linux-gnu/` 下的所有文件解压至 `Umi-OCR/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/lib/` 目录。

修改 `Umi-OCR/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/run.sh`。

增加一行 `LD_LOCATION="$SCRIPT_DIR/lib/ld-linux-x86-64.so.2"`。

最后一行的中间位置增加 `"$LD_LOCATION"`  。这样就不依赖系统本身的 `libc` 库了。

最终的 `run.sh` ：

```
#! /bin/bash -e

# 获取当前脚本路径
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# 获取PaddleOCR-json路径
EXE_LOCATION="$SCRIPT_DIR/bin/PaddleOCR-json"
LIB_LOCATION="$SCRIPT_DIR/lib/"
# 以下一行是增加的
LD_LOCATION="$SCRIPT_DIR/lib/ld-linux-x86-64.so.2"
# 运行PaddleOCR-json
# 以下行的"$LD_LOCATION"是增加的
LD_LIBRARY_PATH="$LIB_LOCATION" "$LD_LOCATION" "$EXE_LOCATION" -models_path="$SCRIPT_DIR/models" "$@"
```

**Comment by hiroi-sora** [comment]
v2.1.4 新版本中，重新编译了 GLIBC 版本更低的依赖项，可解决此问题。请重新下载 Dockerfile 并构建镜像。

**Comment by shaoxinghua0623** [comment]
> 理论上，Docker基础镜像 `debian:11` 在我的测试环境中是可以正确部署的。但可能你的主机系统版本较旧，而Docker容器又使用了主机的部分环境，导致该不兼容现象。我估计，换用新的基础镜像可以解决：

我换了debian:12-slim后，重新编译后，调用API的时候，还是出现下面的错误
` {'code': 803, 'data': "任务提前结束。[Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 16, 'config_path': '简体中文', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 960}\nOCR init fail."}
任务提前结束。[Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 16, 'config_path': '简体中文', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 960}
OCR init fail.
`

我运行了下面的脚本
`/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/run.sh`
结果如下：

![Image](https://github.com/user-attachments/assets/8d7110e2-f49d-4d84-af43-a3ad6864ad86)

请问怎么解决这个问题的，我是先本地部署，部署完调接口的时候出现OCR init fail的错误后，然后用docker部署，发现还是这个错误，然后换了debian的版本，还是这个错误。

**Comment by Gavin1937** [comment]
> > 理论上，Docker基础镜像 `debian:11` 在我的测试环境中是可以正确部署的。但可能你的主机系统版本较旧，而Docker容器又使用了主机的部分环境，导致该不兼容现象。我估计，换用新的基础镜像可以解决：
> 
> 我是采用Docker部署方式进行部署，在部署过程中遇到以下问题：
> 
> 执行以下脚本，结果如下：
> `/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/run.sh`
> ![Image](https://github.com/user-attachments/assets/8d7110e2-f49d-4d84-af43-a3ad6864ad86)
> 
> 但我在实际调用的时候，报下面的错误：
> ![Image](https://github.com/user-attachments/assets/702825ac-3457-4b84-ad57-83469a24b36c)
> 
> 请问怎么解决这个问题？

可能是输入给引擎的参数错了。`config_path`应该是一个指向引擎内models文件夹的`config_xxx.txt`文件的**相对路径**，请看[这里的解释](https://github.com/hiroi-sora/PaddleOCR-json?tab=readme-ov-file#%E8%AF%AD%E8%A8%80%E5%BA%93%E4%B8%8E%E5%88%87%E6%8D%A2%E8%AF%86%E5%88%AB%E8%AF%AD%E8%A8%80)。

因此您可以在test.py文件内将引擎路径设置成
```
/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/run.sh
```
然后再把config_path设置成基于`/app/UmiOCR-data/plugins/linux_x64_PaddleOCR-json_v140_beta/models`文件夹的配置文件的相对路径。
当然，不设置config_path也没问题，run.sh脚本会自动设置models文件夹的路径作，引擎会以此为根目录来默认加载简体中文模型
