### ISSUE TITLE
OCR Result: { code: 803, data: '任务提前结束。[Error] MissionOCR: API object is None.' }

### ISSUE THREAD

**Issue by TIservice** [hiroi-sora/Umi-OCR_runtime_linux#4]
OCR Result: { code: 803, data: '任务提前结束。[Error] MissionOCR: API object is None.' }

![image](https://github.com/user-attachments/assets/32086b0b-7635-47cf-bcff-aad8eb25d055)
是否指令集不支持?

**Comment by hiroi-sora** [comment]
https://github.com/hiroi-sora/Umi-OCR_runtime_linux/issues/3
